version: '3.8'

services:
  app:
    image: webapp-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env  # Specify the path to your .env file
    volumes:
      - .:/app
      - /app/node_modules
